### ISSUE TITLE
Create Example fails if the Web Service is not explicitly chosen

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/webapi#25]
`https://api-test.ala.org.au/admin/example/create?webService=117` fails due to `Property [webService] of class [class au.org.ala.webapi.Example] cannot be null`

The `Web Service` on `/admin/example/create` isn't selectable or changeable when the `webService` parameter is given.

![Screen Shot 2019-11-01 at 2 53 52 pm](https://user-images.githubusercontent.com/82365/68001448-397a2900-fcb8-11e9-946d-caf2eef65188.png)

However, clicking on `Create` always fails with a message about it not being able to be null

![Screen Shot 2019-11-01 at 2 55 03 pm](https://user-images.githubusercontent.com/82365/68001463-426afa80-fcb8-11e9-9263-9d970063bd86.png)

The resulting screen shows the first "Web Service" in the list, but the actual service can be chosen.

**Comment by Rita-C** [comment]
@ansell ,
I managed to create two examples via "New example" button, the first one selected "Fictional service", the second used the default webservice, i.e. no webservice was explicitly chosen from the list.
https://api-test.ala.org.au/admin/example/show/73
https://api-test.ala.org.au/admin/example/show/74

**Comment by ansell** [comment]
I just replicated the issue again so it is still present, at least in Firefox where I am testing it. 

The link I posted above is the one that gets the service auto-populated and you can't change the box. After it fails, you are able to change the service, and it works then. 

This bug is to track the issue of it not working the first time. It may not be a priority if everyone knows they will have to reselect the service and submit again, but it isn't fixed at this point.

**Comment by Rita-C** [comment]
I deleted the comment as I realised you went a different path.

**Comment by Rita-C** [comment]
@ansell fix deployed to test.
There are multiple entry points from the application:
- On web service list page, click "Add example" button of a specific web service
- On view a web service page, click "Create example" button
- From the lastRuns page, click "Add example" link of a specific web service

**Comment by ansell** [comment]
This is still broken for me.

Steps:

1. Visit https://api-test.ala.org.au/admin/example/create?webService=117
2. Fill in `Name` and `Description`
3. Click on `Create`

**Comment by ansell** [comment]
Although the URL in the steps above is still accepted and shows a form as expected, the URL under `Add Example` for an existing web service in the interface has changed to the following, which does work with the `webService` parameter:

`https://api-test.ala.org.au/admin/example/createForWS?webService=1`
